### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/Book-Shop#1]
Add valuable content to the readme file like other hacktoberfest repository.
You need to add details of this project and it will available in the repo discussions. please check it and add that content to the readme and send a PR

**Comment by MadhushaPrasad** [comment]
✨ hacktoberfest 2022
🌱 Contributing to hacktoberfest 2022
Welcome to hacktoberfest 2022 Public Repository. 👨🏻‍💻

**Comment by SayuruRehan** [comment]
updated readme. PR sent

**Comment by MadhushaPrasad** [comment]
@SayuruRehan next time before sent the PR, Please be look that Issue assigned or not, If not ask from that repo owner to assign you first.
